<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title>PHPWord</title>
<style>
* {font-family: Arial; font-size: 10pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width: 100%;}
td {border: 1px solid black;}
.rightTab {}
.leftTab {}
.leftRight {}
</style>
</head>
<body>
<table>
<tr>
<td>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">ĐƠN VỊ CHỦ QUẢN</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 12pt; font-weight: bold;">TRUNG TÂM: Trung tâm 1</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 12pt;">Số: 12 /BC: 12</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 12pt; font-weight: bold;">VV  báo cáo tình hình hoạt động</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 12pt; font-weight: bold;">Trung tâm 6 tháng đầu năm 2017</span></p>
</td>
<td>
<p style="text-align: center;"><span style="font-family: 'Times New Roman'; font-size: 12pt;">Cộng hòa Xã hội Chủ nghĩa Việt Nam</span></p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">Độc lập - Tự Do - Hạnh Phúc</span></p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman'; font-size: 12pt;">----------------</span></p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman'; font-size: 12pt; font-style: italic;">Hà Nội, Ngày 19/07/2017</span></p>
</td>
</tr>
</table>
<p></p>
<p></p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">Kính gửi: Sở Giáo dục và Đào tạo Hà Nội</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Thực hiện Công văn số 12/SGD&amp;ĐT-GDTX-CN ngày 12 tháng 12 năm 2012 của Sở Giáo dục và Đào tạo Hà Nội về việc báo cáo định kỳ kết quả hoạt động 6 tháng đầu năm 2017 đối với các Trung tâm: giáo dục/đào tạo có vốn ĐTNN;VPĐDGDNN; NN, NN-TH; nghiệp vụ chuyên ngành và các Tổ chức tư vấn du học trên địa bàn Thành phố, Trung tâm Trung tâm 1 báo cáo tình hình và kết quả hoạt động 6 tháng đầu năm 2017 như sau:</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">1- Tính pháp lý của cơ sở</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">1.1. Thông tin doanh nghiệp</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Giấy chứng nhận đầu tư/đăng ký doanh nghiệp</span></p>
<p></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Số: 12, Ngày cấp: 19/07/2017, nơi cấp: Thanh Xuân - Hà Nội</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Địa chỉ trụ sở chính: </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">Thanh Xuân - Hà Nội</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Điện thoại: 0912347127, Fax: 912932183, Email: trungtam@gmail.com</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Website: trungtam1.com.vn</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Loại hình doanh nghiệp: Tự do</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Thời hạn hoạt động: 19/08/2017</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Mã số thuế: THUE1238217391273VN</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Vốn đăng ký/điều lệ: 100000000000000000 VNĐ</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Vốn góp thực hiện dự án đăng ký/cho Trung tâm: 20000000000000000 VNĐ</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Người đại diện pháp luật:</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Họ và tên: Nguyễn Văn A, Quốc tịch: Việt Nam</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Điện thoại di đông: 09282831712, Email liên hệ: nguyenvana@gmail.com</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Nơi ở hiện tại: Hà Nội</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">1.2. Thông tin Trung tâm: giáo dục/đào tạo có vốn ĐTNN; NN; NN-TH; nghiệp vụ chuyên ngành, sau đây gọi tắt là Trung tâm.</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Tên trung tâm: </span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">(tiếng Việt Nam): </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">Trung Tâm</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">(tiếng Anh, tên giao dịch): </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">Center</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Quyết định cho phép thành lập</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Số: 12 Ngày cấp: 19/07/2017 Nơi cấp: Hà Nội</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Quyết định/Chứng nhận cho phép hoạt động</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Số: 12 Ngày cấp: 20/07/2017 Nơi cấp: Hà Nội</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Giám đốc trung tâm:</span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">(Ghi rõ từng trung tâm)</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Họ và tên: Nguyễn Văn B, Quốc tịch: Việt Nam</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Điện thoại di động: 0928218172, Email liên hệ: nguyenvanb@gmail.com</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Nơi ở hiện tại: Hà Nội - Việt Nam</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Địa chỉ cơ sở đào tạo: </span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">(ghi rõ từng cơ sở) </span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold; font-style: italic;">Nội dung hoạt động được cấp phép:</span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">(ghi theo Quyết định/Chứng nhận hoạt động)</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">2. Báo cáo kết quả hoạt động 6 tháng đầu năm 2017</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">2.1. Báo cáo thống kê số liệu đối với Trung tâm: </span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">báo cáo theo mẫu M1a</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">2.2. Báo cáo danh sách, thông tin và hồ sơ đối với cán bộ, giám đốc làm việc tại Trung tâm: </span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">báo cáo theo mẫu M1b</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">2.3. Báo cáo danh sách, thông tin và hồ sơ đối với lao động nước ngoài làm việc tại các trường đại học ở Hà Nội mà Trung tâm có hợp tác/liên kết: </span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">báo cáo theo mẫu M1c</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">2.4. Đánh giá chung về kết quả hoạt động của Trung tâm 6 tháng đầu năm 2017</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">2.5. Những khó khăn vướng mắc: </span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Vướng mắc 1</span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">2.6. Đề xuất, kiến nghị với cơ quan chức năng: </span></p>
<p><span style="font-family: 'Times New Roman'; font-size: 13pt;">Kiến Nghị 1</span></p>
<p></p>
<p style="text-align: right;"><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">Giám đốc</span></p>
<p style="text-align: right;"><span style="font-family: 'Times New Roman'; font-size: 13pt; font-style: italic;">(Ký tên và đóng dấu)</span></p>
</body>
</html>
